### ISSUE TITLE
Is VIRTUAL_NETWORK env var really mandatory?

### ISSUE THREAD

**Issue by coodix** [gilyes/docker-nginx-letsencrypt-sample#1]
There are two example services and they both have environment variable VIRTUAL_NETWORK.

Is it really necessary?

Actual nginx.tmpl doesn't have any logic base on this var.

And why have you removed networks section from docker-compose.yml? Without that it's impossible to make it's working if the external service is located outside the same docker-compose.yml. For example it could be launched manually or through different docker-compose.yml on the same server.

**Comment by gilyes** [comment]
Yes, the network has to be explicitly specified if you want to talk to external services, but in this simple example all services are connected to the default/implicit network created by compose. 

And you are right, the VIRTUAL_NETWORK environment variable is useless, just got left in there from a prior version.

**Comment by coodix** [comment]
Thanks for explanation!
