### ISSUE TITLE
File upload size

### ISSUE THREAD

**Issue by Sch-Tomi** [gilyes/docker-nginx-letsencrypt-sample#13]
Hi!

Im lost a little bit. I need to set a client_max_body_size paramter for the proxy (i hope). 
So if im right i have to edit the nginx.tmpl file. Could you help me out where should i put this line?

Btw Thanks for the repo its really useful :)

**Comment by gilyes** [comment]
I think you could either add that setting directly to all `server` blocks in `nginx.tmpl` or follow the instructions in https://github.com/jwilder/nginx-proxy#proxy-wide to add custom config files that are pulled in by `nginx.tmpl` (examples there are `docker run` commands so you'll likely want to convert those to mappings in your`docker-compose.yml`).

**Comment by Sch-Tomi** [comment]
Thanks! Its worked :+1:

**Comment by TwiN** [comment]
@Sch-Tomi could you close the issue if your problem has been resolved?

**Comment by Sch-Tomi** [comment]
Ofc sry
